name: Schedule

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  playground:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: FeedsFetcher
        uses: llun/feeds@2.6
with:
  opmlFile: feeds.opml
  
