name: VIP RSS

on:
  push:
    branches:
      - main
    schedule:
        - cron: "0 * * * *"

jobs:
  feeds:
    runs-on: ubuntu-latest
    name: Build static feeds site
    steps:
      - name: Run Action
        uses: llun/feeds@2.6
        with:
          storageType: files
          customDomain: rss.veryinter.net
          opmlFile: viprss.opml
  
